In [1]:
import numpy as np

data = np.array(np.random.permutation(np.arange(stop=5 * 5 * 3)).reshape((3, 5, 5)), dtype=float)

kernels = np.array(
    np.random.permutation(np.arange(stop=3 * 3 * 4)).reshape((4, 3, 3)), dtype=float
)

bias = 0

In [2]:
print("data:", data, "kernels:", kernels, "bias:", bias, sep='\n')

data:
[[[73. 10. 43. 16. 37.]
  [ 1. 52. 74. 22.  7.]
  [19. 26. 42. 50. 51.]
  [59. 57.  9. 53.  4.]
  [54. 36. 71. 39. 56.]]

 [[20. 29. 58. 11. 17.]
  [18. 32. 14. 46.  0.]
  [31. 44. 45. 28. 23.]
  [35. 60. 12. 64. 15.]
  [63.  6. 69. 40. 24.]]

 [[21. 25.  2. 68. 61.]
  [72.  8. 30. 38. 66.]
  [47.  3. 34. 27. 65.]
  [48.  5. 55. 49. 41.]
  [13. 70. 33. 62. 67.]]]
kernels:
[[[13. 11. 24.]
  [25. 30. 20.]
  [22. 21. 14.]]

 [[17.  8. 28.]
  [ 2. 23. 18.]
  [26.  5. 33.]]

 [[ 3.  4. 10.]
  [31.  9. 12.]
  [32. 19. 16.]]

 [[35. 27.  7.]
  [34.  1.  6.]
  [15. 29.  0.]]]
bias:
0


## Naive

In [3]:
from naive import conv2d as naive_conv

In [4]:
print(naive_conv(data, kernels, bias))

[[[17414. 17822. 19547.]
  [18812. 19197. 19405.]
  [21332. 21521. 22969.]]

 [[16636. 15346. 17977.]
  [16448. 19325. 14843.]
  [19728. 18559. 21893.]]

 [[13120. 13055. 15418.]
  [15015. 14424. 14418.]
  [17261. 17338. 17310.]]

 [[13905. 14172. 16391.]
  [16260. 14415. 18510.]
  [16817. 18474. 17837.]]]


## im2col

In [5]:
from im2col import im2col
from im2col import conv2d as im2col_conv2d

In [6]:
print(im2col_conv2d(data, kernels, bias))

[[[17414. 17822. 19547.]
  [18812. 19197. 19405.]
  [21332. 21521. 22969.]]

 [[16636. 15346. 17977.]
  [16448. 19325. 14843.]
  [19728. 18559. 21893.]]

 [[13120. 13055. 15418.]
  [15015. 14424. 14418.]
  [17261. 17338. 17310.]]

 [[13905. 14172. 16391.]
  [16260. 14415. 18510.]
  [16817. 18474. 17837.]]]


## Memory strides