In [7]:
import numpy as np

F = 5
C = 3
K = 3

data = np.array(np.random.permutation(np.arange(stop=F * F * C)).reshape((C, F, F)), dtype=float)

kernels = np.array(
    np.random.permutation(np.arange(stop=K * K * C)).reshape((C, K, K)), dtype=float
)

bias = 0

In [8]:
print("data:", data, "kernels:", kernels, "bias:", bias, sep='\n')

data:
[[[31. 71. 34. 39. 61.]
  [10. 26. 50. 22.  9.]
  [32. 72. 51. 49.  8.]
  [35. 14. 43. 58. 54.]
  [46. 74. 17. 13. 47.]]

 [[15.  0. 28. 53. 55.]
  [48. 24. 42.  1. 12.]
  [52. 21. 11. 36. 45.]
  [38. 41. 40. 25. 59.]
  [ 3. 64. 68. 16. 57.]]

 [[ 4. 23. 33.  5.  7.]
  [37. 63. 73. 67. 19.]
  [ 2. 69. 27. 56. 30.]
  [18. 60. 65. 66. 29.]
  [70. 62. 20. 44.  6.]]]
kernels:
[[[ 1. 20. 19.]
  [14. 24. 18.]
  [ 0. 21. 26.]]

 [[ 2.  9.  7.]
  [10. 12.  6.]
  [11.  8. 15.]]

 [[ 4. 16. 22.]
  [17.  5. 13.]
  [23. 25.  3.]]]
bias:
0


## Naive

In [9]:
from naive import conv2d as naive_conv

In [10]:
print(naive_conv(data, kernels, bias))

[[13605. 13496. 11406.]
 [14377. 17239. 13974.]
 [15461. 14112. 14144.]]


## im2col

In [11]:
from im2col import im2col
from im2col import conv2d as im2col_conv2d

In [12]:
print(im2col_conv2d(data, kernels, bias))

[[13605. 13496. 11406.]
 [14377. 17239. 13974.]
 [15461. 14112. 14144.]]


## Memory strides